---
- name: "System VDOM settings"
  hosts: "firewalls"
  gather_facts: false

  tasks:
    - name: "Backing up the System VDOM settings"
      ansible.builtin.include_role:
        name: "system_vdom"
        tasks_from: "backup.yml"
