---
# List of all Ansible Galaxy collections required by this project.
ansible_galaxy_collections:
  - { name: "ansible.posix", state: "latest" } # POSIX utilities.
  - { name: "community.general", state: "latest" } # General purpose Ansible roles and collections.
  - { name: "fortinet.fortios", state: "latest" } # To work with Fortigate.
  - { name: "community.hashi_vault", state: "latest" } # HashiCorp Vault.
  - { name: "community.crypto", state: "latest" } # Cryptography and HashiCorp Vault.
