---
- name: "Installing Ansible Galaxy collections"
  become: false
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/ansible-galaxy"
  vars:
    packages: "{{ ansible_galaxy_collections }}"

- name: "Debug Ansible Galaxy installation output"
  tags: ["never", "debug"]
  ansible.builtin.debug:
    msg:
      - "{{ output }}"
