---
certificate_name: "firewall-2026"
temp_certificate_name: "Fortinet_Factory"

ssl_path: "ssl"
certificate_base_name: "firewall_01.lan.home"

certificate_file: "{{ ssl_path ~ '/' ~ certificate_base_name }}.crt"
private_key_file: "{{ ssl_path ~ '/' ~ certificate_base_name }}.key"
